title: Project Blog
author: Richard J.
email: techpowerawaits at outlook dot com
description: > # this means to ignore newlines until "baseurl:"
  This blog contains news of the latest projects written by TechPowerAwaits.

# social links
linkedin_username: techpowerawaits # DO NOT include the @ character, or else the build will fail!
github_username:  techpowerawaits # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
